export const ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  MEMBER: 'member',
  GUEST: 'guest',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_HIERARCHY: Record<Role, number> = {
  [ROLES.OWNER]: 4,
  [ROLES.ADMIN]: 3,
  [ROLES.MEMBER]: 2,
  [ROLES.GUEST]: 1,
};

export const WORKSPACE_PERMISSIONS = {
  VIEW_WORKSPACE: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER, ROLES.GUEST],
  UPDATE_WORKSPACE: [ROLES.OWNER, ROLES.ADMIN],
  DELETE_WORKSPACE: [ROLES.OWNER],
  INVITE_MEMBERS: [ROLES.OWNER, ROLES.ADMIN],
  REMOVE_MEMBERS: [ROLES.OWNER, ROLES.ADMIN],
  MANAGE_ROLES: [ROLES.OWNER, ROLES.ADMIN],
  CREATE_BOARD: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  VIEW_ALL_BOARDS: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  MANAGE_SETTINGS: [ROLES.OWNER, ROLES.ADMIN],
  BILLING_ACCESS: [ROLES.OWNER],
} as const;

export const BOARD_PERMISSIONS = {
  VIEW_BOARD: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER, ROLES.GUEST],
  UPDATE_BOARD: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  DELETE_BOARD: [ROLES.OWNER, ROLES.ADMIN],
  CREATE_CARD: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  UPDATE_ANY_CARD: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  DELETE_ANY_CARD: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  MANAGE_LABELS: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  MANAGE_LISTS: [ROLES.OWNER, ROLES.ADMIN, ROLES.MEMBER],
  ARCHIVE_BOARD: [ROLES.OWNER, ROLES.ADMIN],
} as const;

export function hasPermission(
  userRole: Role,
  allowedRoles: readonly Role[]
): boolean {
  return allowedRoles.includes(userRole);
}

export function isAtLeastRole(userRole: Role, requiredRole: Role): boolean {
  return ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[requiredRole];
}
